-- Schéma relationnel Vite & Gourmand (MySQL 8.4)
-- Exécuter : mysql -u root -p viteetgourmand < database/schema.sql

CREATE DATABASE IF NOT EXISTS viteetgourmand CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE viteetgourmand;

CREATE TABLE allergen (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(80) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE contact_message (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, title VARCHAR(150) NOT NULL, message LONGTEXT NOT NULL, is_processed TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE diet (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(50) NOT NULL, slug VARCHAR(80) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE dish (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(150) NOT NULL, description LONGTEXT DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, type VARCHAR(30) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE theme (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(50) NOT NULL, slug VARCHAR(80) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL, address LONGTEXT NOT NULL, postal_code VARCHAR(20) NOT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE menu (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(150) NOT NULL, slug VARCHAR(180) NOT NULL, description LONGTEXT NOT NULL, conditions_text LONGTEXT DEFAULT NULL, min_people INT NOT NULL, price_per_person NUMERIC(10, 2) NOT NULL, stock_quantity INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, theme_id INT NOT NULL, diet_id INT NOT NULL, INDEX IDX_MENU_THEME (theme_id), INDEX IDX_MENU_DIET (diet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE menu_dish (menu_id INT NOT NULL, dish_id INT NOT NULL, INDEX IDX_MENU_DISH_MENU (menu_id), INDEX IDX_MENU_DISH_DISH (dish_id), PRIMARY KEY(menu_id, dish_id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE dish_allergen (dish_id INT NOT NULL, allergen_id INT NOT NULL, INDEX IDX_DISH_ALLERGEN_DISH (dish_id), INDEX IDX_DISH_ALLERGEN_ALLERGEN (allergen_id), PRIMARY KEY(dish_id, allergen_id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE menu_image (id INT AUTO_INCREMENT NOT NULL, filename VARCHAR(255) NOT NULL, alt_text VARCHAR(255) DEFAULT NULL, position INT NOT NULL, created_at DATETIME NOT NULL, menu_id INT NOT NULL, INDEX IDX_MENU_IMAGE_MENU (menu_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE menu_order (id INT AUTO_INCREMENT NOT NULL, order_number VARCHAR(50) NOT NULL, service_date DATE NOT NULL, delivery_time TIME NOT NULL, delivery_address VARCHAR(255) NOT NULL, delivery_city VARCHAR(100) NOT NULL, delivery_place VARCHAR(255) DEFAULT NULL, people_count INT NOT NULL, menu_price NUMERIC(10, 2) NOT NULL, delivery_price NUMERIC(10, 2) NOT NULL, discount_amount NUMERIC(10, 2) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, status VARCHAR(50) NOT NULL, material_loan TINYINT(1) NOT NULL DEFAULT 0, material_returned TINYINT(1) NOT NULL, cancellation_reason LONGTEXT DEFAULT NULL, cancellation_contact_mode VARCHAR(30) DEFAULT NULL, distance_km NUMERIC(8, 2) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, menu_id INT NOT NULL, INDEX IDX_ORDER_USER (user_id), INDEX IDX_ORDER_MENU (menu_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE opening_hour (id INT AUTO_INCREMENT NOT NULL, day_of_week VARCHAR(20) NOT NULL, opening_time TIME DEFAULT NULL, closing_time TIME DEFAULT NULL, is_closed TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE order_status_history (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(50) NOT NULL, comment LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, menu_order_id INT NOT NULL, changed_by_id INT DEFAULT NULL, INDEX IDX_HISTORY_ORDER (menu_order_id), INDEX IDX_HISTORY_USER (changed_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE review (id INT AUTO_INCREMENT NOT NULL, rating INT NOT NULL, comment LONGTEXT NOT NULL, status VARCHAR(30) NOT NULL, created_at DATETIME NOT NULL, moderated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, menu_order_id INT NOT NULL, moderated_by_id INT DEFAULT NULL, INDEX IDX_REVIEW_USER (user_id), UNIQUE INDEX UNIQ_REVIEW_ORDER (menu_order_id), INDEX IDX_REVIEW_MODERATOR (moderated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, INDEX IDX_RESET_USER (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_MESSENGER (queue_name, available_at, delivered_at, id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4;

ALTER TABLE menu ADD CONSTRAINT FK_MENU_THEME FOREIGN KEY (theme_id) REFERENCES theme (id);
ALTER TABLE menu ADD CONSTRAINT FK_MENU_DIET FOREIGN KEY (diet_id) REFERENCES diet (id);
ALTER TABLE menu_dish ADD CONSTRAINT FK_MENU_DISH_MENU FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE;
ALTER TABLE menu_dish ADD CONSTRAINT FK_MENU_DISH_DISH FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE;
ALTER TABLE dish_allergen ADD CONSTRAINT FK_DISH_ALLERGEN_DISH FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE;
ALTER TABLE dish_allergen ADD CONSTRAINT FK_DISH_ALLERGEN_ALLERGEN FOREIGN KEY (allergen_id) REFERENCES allergen (id) ON DELETE CASCADE;
ALTER TABLE menu_image ADD CONSTRAINT FK_MENU_IMAGE_MENU FOREIGN KEY (menu_id) REFERENCES menu (id);
ALTER TABLE menu_order ADD CONSTRAINT FK_ORDER_USER FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE menu_order ADD CONSTRAINT FK_ORDER_MENU FOREIGN KEY (menu_id) REFERENCES menu (id);
ALTER TABLE order_status_history ADD CONSTRAINT FK_HISTORY_ORDER FOREIGN KEY (menu_order_id) REFERENCES menu_order (id);
ALTER TABLE order_status_history ADD CONSTRAINT FK_HISTORY_USER FOREIGN KEY (changed_by_id) REFERENCES user (id);
ALTER TABLE review ADD CONSTRAINT FK_REVIEW_USER FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE review ADD CONSTRAINT FK_REVIEW_ORDER FOREIGN KEY (menu_order_id) REFERENCES menu_order (id);
ALTER TABLE review ADD CONSTRAINT FK_REVIEW_MODERATOR FOREIGN KEY (moderated_by_id) REFERENCES user (id);
ALTER TABLE reset_password_request ADD CONSTRAINT FK_RESET_USER FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
